### ISSUE TITLE
NodeJs upgrade?

### ISSUE THREAD

**Issue by glynhudson** [jeremypoulter/openevse_wifi_gui#1]
Hi @jeremypoulter,

Nice work, I've just tired to test. I ran `sudo npm install` then `npm run build`, I get the following error. Do I need to upgrade nodejs? I'm curently running V8.10.0? 

```
glyn@glyn-desktop:~/Documents/openevse_wifi_gui$ npm run build

> openevse_wifi_gui@1.0.0 build /home/glyn/Documents/openevse_wifi_gui
> webpack

/home/glyn/Documents/openevse_wifi_gui/node_modules/webpack-cli/bin/cli.js:235
				throw err;
				^

Error: Cannot find module 'uglifyjs-webpack-plugin'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (/home/glyn/Documents/openevse_wifi_gui/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/glyn/Documents/openevse_wifi_gui/webpack.config.js:3:24)
    at Module._compile (/home/glyn/Documents/openevse_wifi_gui/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/home/glyn/Documents/openevse_wifi_gui/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/home/glyn/Documents/openevse_wifi_gui/node_modules/webpack-cli/bin/convert-argv.js:115:13)
    at requireConfig (/home/glyn/Documents/openevse_wifi_gui/node_modules/webpack-cli/bin/convert-argv.js:117:6)
    at /home/glyn/Documents/openevse_wifi_gui/node_modules/webpack-cli/bin/convert-argv.js:124:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/glyn/Documents/openevse_wifi_gui/node_modules/webpack-cli/bin/convert-argv.js:122:15)
    at yargs.parse (/home/glyn/Documents/openevse_wifi_gui/node_modules/webpack-cli/bin/cli.js:232:39)
    at Object.parse (/home/glyn/Documents/openevse_wifi_gui/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /home/glyn/Documents/openevse_wifi_gui/node_modules/webpack-cli/bin/cli.js:210:8
    at Object.<anonymous> (/home/glyn/Documents/openevse_wifi_gui/node_modules/webpack-cli/bin/cli.js:500:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/glyn/Documents/openevse_wifi_gui/node_modules/webpack/bin/webpack.js:155:2)
    at Module._compile (module.js:652:30)

npm ERR! Linux 4.15.0-43-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! openevse_wifi_gui@1.0.0 build: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openevse_wifi_gui@1.0.0 build script 'webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the openevse_wifi_gui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs openevse_wifi_gui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls openevse_wifi_gui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/glyn/Documents/openevse_wifi_gui/npm-debug.log
glyn@glyn-desktop:~/Documents/openevse_wifi_gui$ nodejs --version
v8.10.0
```

**Comment by jeremypoulter** [comment]
Don't think so, you don't need the `sudo` for the `npm install`, that may have have installed the dependencies in the wrong location. Will try getting Travis CI setup.

**Comment by jeremypoulter** [comment]
Travis was failing with versions 6 and 7, but now fixed
